version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: my_password
    depends_on:
      - db
  db:
    image: "postgres:13"
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  data:
